### ISSUE TITLE
Line breaks in dialogue should be preserved

### ISSUE THREAD

**Issue by allenwlee** [HendrikNoeller/Writer-Mac#2]
Example:  In Plain Text, using a line break:

```
        HAMLET
To be, or not to be, that is the question:
Whether 'tis Nobler in the mind to suffer
```

In preview, incorrectly becomes:

```
        HAMLET
To be, or not to be, that is the question: Whether 'tis Nobler in the mind to suffer
```

**Comment by HendrikNoeller** [comment]
The issue seemed to be inside the FNHTMLScript supplied by the fountain framework, which did not translate `\n` to `<br>` as html ignores regular line breaks and only reacts to `<br>`.

**Comment by allenwlee** [comment]
OK.  I note that it works in http://www.screenplain.com/.  Maybe they added that translation themselves

**Comment by HendrikNoeller** [comment]
I have implemented a translation as well, which will be inside the next commit

**Comment by allenwlee** [comment]
Excellent, thank you.
